---
- name: Upgrade OS System & Install dependencies
  yum:
    name: "*"
    state: latest

- name: Enable Epel Release
  yum:
    name: epel-release
    enablerepo: epel-release

- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present

- name: Cleaning unused packs
  yum:
    autoremove: yes
