---
- name: Upgrade OS System & Install dependencies
  yum:
    name: "*"
    state: latest

- name: Enable Epel Release
  yum_repository:
    name: epel
    description: Epel YUM Repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no
