---
  - name: Install dependencies
    yum:
      name:
        - vim
        - mlocate
        - bash-completion
        - net-tools
        - wget
        - curl
        - git

  - name: Firebird Download
    yum:
      name: firebird
      state: latest


