---
  - name: Install dependencies
    yum:
      name:
        - vim
        - mlocate
        - bash-completion
        - net-tools
        - wget
        - curl
        - git

  - name: Firebird Installation
    yum:
      name: firebird
      state: latest

  - name: Starting Firebird
    systemd:
      state: started
      name: firebird-superserver
      enabled: yes

